naver_field_master = {
    "Campaign_report": [
        "customerID",
        "campaignID",
        "campaignName",
        "campaignType",
        "deliveryMethod",
        "usingPeriod",
        "periodStartDate",
        "periodEndDate",
        "regTm",
        "delTm",
        "on/off",
        "sharedBudgetID",
    ],
    "Adgroup_report": [
        "customerID",
        "adGroupID",
        "campaignID",
        "adGroupName",
        "adGroupBidamount",
        "on/off",
        "usingcontentsnetworkbid",
        "contentsnetworkbid",
        "pcNetworkBiddingweight",
        "mobileNetworkBiddingweight",
        "businessChannelId(Mobile)",
        "businessChannelId(PC)",
        "regTm",
        "delTm",
        "contentType",
        "adGroupType",
        "sharedBudgetID",
        "usingExpandedSearch",
    ],

    "Keyword_report": [
        "customerID",
        "adGroupID",
        "adKeywordID",
        "adKeyword",
        "adKeywordBidAmount",
        "landingURL(PC)",
        "landingURL(Mobile)",
        "on/off",
        "adKeywordInspectStatus",
        "usingAdGroupBidAmount",
        "regTm",
        "delTm",
        "adKeywordType",
    ],

    "ShoppingProduct_report": [
        "customerID",
        "adGroupID",
        "adID",
        "adCreativeInspectStatus",
        "on/off",
        "adProductName",
        "adImageUrl",
        "bid",
        "usingAdgroupBidAmount",
        "adLinkStatus",
        "regTm",
        "delTm",
        "productID",
        "productIDOfMall",
        "productName",
        "productImageUrl",
        "pcLandingUrl",
        "mobileLandingUrl",
        "price",
        "deliveryFee",
        "naverShoppingCategory1",
        "naverShoppingCategory2",
        "naverShoppingCategory3",
        "naverShoppingCategory4",
        "naverShoppingCategoryID1",
        "naverShoppingCategoryID2",
        "naverShoppingCategoryID3",
        "naverShoppingCategoryID4",
        "categoryNameofMall",
        "unUsed"
    ],

    "AD_report": [
        "date",
        "customerID",
        "campaignID",
        "adGroupID",
        "adKeywordID",
        "adID",
        "businessChannelID",
        "mediacode",
        "pcMobileType",
        "impressions",
        "clicks",
        "cost",
        "sumofADrank",
        "viewcount",
    ],
    "AD_CONVERSION_report": [
        "date",
        "customerID",
        "campaignID",
        "adGroupID",
        "adKeywordID",
        "adID",
        "businessChannelID",
        "mediacode",
        "pcMobileType",
        "conversionMethod",
        "conversionType",
        "conversionCount",
        "salesByConversion",
    ],
    "SHOPPINGKEYWORD_DETAIL_report" : [
        "date",
        "customerID",
        "campaignID",
        "adGroupID",
        "searchKeyword",
        "adID",
        "businessChannelID",
        "hours",
        "regionCode",
        "mediaCode",
        "pcMobileType",
        "impressions",
        "clicks",
        "cost",
        "sumofADrank",
        "viewcount"
    ],
    "SHOPPINGKEYWORD_CONVERSION_DETAIL_report":[
        "date",
        "customerID",
        "campaignID",
        "adGroupID",
        "searchKeyword",
        "adID",
        "businessChannelID",
        "hours",
        "regionCode",
        "mediaCode",
        "pcMobileType",
        "conversionMethod",
        "conversionType",
        "conversionCount",
        "salesByConversion"
    ]
}

naver_master_config = {
    "Campaign": {"id": "campaignID", "name": "campaignName"},
    "Adgroup": {"id": "adGroupID", "name": "adGroupName"},
    "Keyword": {"id": "adKeywordID", "name": "adKeyword"},
    "ShoppingProduct": {"id": "adID", "name": "adProductName"}
}


naver_vaild_fields = {
    "AD": [
        "date",
        "campaignID",
        "campaignName",
        "adGroupID",
        "adGroupName",
        "adKeywordID",
        "adKeyword",
        "impressions",
        "clicks",
        "cost",
        "sumofADrank",
    ],
    "AD_CONVERSION": [
        "date",
        "campaignID",
        "campaignName",
        "adGroupID",
        "adGroupName",
        "adKeywordID",
        "adKeyword",
        "conversionType",
        "conversionCount",
        "salesByConversion",
    ],
    "SHOPPINGKEYWORD_DETAIL": [
        "date",
        "campaignID",
        "campaignName",
        "adGroupID",
        "adGroupName",
        "searchKeyword",
        "adID",
        "adProductName",
        "impressions",
        "clicks",
        "cost",
        "sumofADrank",
    ],
    "SHOPPINGKEYWORD_CONVERSION_DETAIL": [
        "date",
        "campaignID",
        "campaignName",
        "adGroupID",
        "adGroupName",
        "searchKeyword",
        "adID",
        "adProductName",
        "conversionType",
        "conversionCount",
        "salesByConversion",
    ]
}